use SalaryAppContext;
INSERT INTO dbo.Cities(CityName) VALUES(N'آيسک  خراسان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اب  بر');
INSERT INTO dbo.Cities(CityName) VALUES(N'اب  سرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابادان');
INSERT INTO dbo.Cities(CityName) VALUES(N'آباده');
INSERT INTO dbo.Cities(CityName) VALUES(N'اباده طشک');
INSERT INTO dbo.Cities(CityName) VALUES(N'اب  پخش');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابدانان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابرکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابريشم');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابوزيداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابوموسي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابيک  شهرستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'احمداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'احمدسرگوراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'اديمي');
INSERT INTO dbo.Cities(CityName) VALUES(N'اذرشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارادان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اراک');
INSERT INTO dbo.Cities(CityName) VALUES(N'اران  وبيدگل');
INSERT INTO dbo.Cities(CityName) VALUES(N'اردبيل');
INSERT INTO dbo.Cities(CityName) VALUES(N'اردستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اردکان  يزد');
INSERT INTO dbo.Cities(CityName) VALUES(N'اردل');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارزوئيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارسنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارشق');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارگدازي');
INSERT INTO dbo.Cities(CityName) VALUES(N'اروميه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اروندکنار');
INSERT INTO dbo.Cities(CityName) VALUES(N'ازادشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'استانه  اشرفيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ازنا');
INSERT INTO dbo.Cities(CityName) VALUES(N'ازندريان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ازوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اژيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسالم');
INSERT INTO dbo.Cities(CityName) VALUES(N'استارا');
INSERT INTO dbo.Cities(CityName) VALUES(N'استانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'استهبان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسفراين');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسفرورين');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسکو');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسلام ابادغرب');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسلامشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسلاميه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشترينان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشتهارد');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشتيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشخانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشکذر');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشکنان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشلي برون');
INSERT INTO dbo.Cities(CityName) VALUES(N'اصفهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اصلاندوز');
INSERT INTO dbo.Cities(CityName) VALUES(N'اغاجاري');
INSERT INTO dbo.Cities(CityName) VALUES(N'افشار');
INSERT INTO dbo.Cities(CityName) VALUES(N'افوس');
INSERT INTO dbo.Cities(CityName) VALUES(N'اقباليه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اق  قلا');
INSERT INTO dbo.Cities(CityName) VALUES(N'اقليد');
INSERT INTO dbo.Cities(CityName) VALUES(N'اکبراباد/مهاجر');
INSERT INTO dbo.Cities(CityName) VALUES(N'الاشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'الشتر');
INSERT INTO dbo.Cities(CityName) VALUES(N'الوارگرمسيري');
INSERT INTO dbo.Cities(CityName) VALUES(N'الوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'الوت');
INSERT INTO dbo.Cities(CityName) VALUES(N'الوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'اليگودرز');
INSERT INTO dbo.Cities(CityName) VALUES(N'امام حسن');
INSERT INTO dbo.Cities(CityName) VALUES(N'امل');
INSERT INTO dbo.Cities(CityName) VALUES(N'اميديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اميراباد دامغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اميرکلا');
INSERT INTO dbo.Cities(CityName) VALUES(N'اميريه  دامغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'انابد');
INSERT INTO dbo.Cities(CityName) VALUES(N'انار');
INSERT INTO dbo.Cities(CityName) VALUES(N'انارک');
INSERT INTO dbo.Cities(CityName) VALUES(N'انديکا');
INSERT INTO dbo.Cities(CityName) VALUES(N'انديمشک');
INSERT INTO dbo.Cities(CityName) VALUES(N'انزاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'انزل');
INSERT INTO dbo.Cities(CityName) VALUES(N'انگوت');
INSERT INTO dbo.Cities(CityName) VALUES(N'انگوران');
INSERT INTO dbo.Cities(CityName) VALUES(N'اوج');
INSERT INTO dbo.Cities(CityName) VALUES(N'اوز');
INSERT INTO dbo.Cities(CityName) VALUES(N'اهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'اهرم');
INSERT INTO dbo.Cities(CityName) VALUES(N'اهل');
INSERT INTO dbo.Cities(CityName) VALUES(N'اهواز');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايجرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايذه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايرانشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايزدخواست');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايلام');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايلخچي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايوانکي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايواوغلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ئيلاق');
INSERT INTO dbo.Cities(CityName) VALUES(N'باب  انار');
INSERT INTO dbo.Cities(CityName) VALUES(N'بابل');
INSERT INTO dbo.Cities(CityName) VALUES(N'بابل کنار');
INSERT INTO dbo.Cities(CityName) VALUES(N'بابلسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'باجگيران');
INSERT INTO dbo.Cities(CityName) VALUES(N'باخرز');
INSERT INTO dbo.Cities(CityName) VALUES(N'بادرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'بازرگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بازفت');
INSERT INTO dbo.Cities(CityName) VALUES(N'باسمنج');
INSERT INTO dbo.Cities(CityName) VALUES(N'باشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'باغ بهادران');
INSERT INTO dbo.Cities(CityName) VALUES(N'باغ ملک');
INSERT INTO dbo.Cities(CityName) VALUES(N'باغين');
INSERT INTO dbo.Cities(CityName) VALUES(N'بافت');
INSERT INTO dbo.Cities(CityName) VALUES(N'بافق');
INSERT INTO dbo.Cities(CityName) VALUES(N'باقرشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'بام  وصفي آباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'باوي');
INSERT INTO dbo.Cities(CityName) VALUES(N'بايک');
INSERT INTO dbo.Cities(CityName) VALUES(N'باينگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بجستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بجنورد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بخشايش');
INSERT INTO dbo.Cities(CityName) VALUES(N'بدره');
INSERT INTO dbo.Cities(CityName) VALUES(N'برازجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گزوبرخوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'برداسکن');
INSERT INTO dbo.Cities(CityName) VALUES(N'بردخون');
INSERT INTO dbo.Cities(CityName) VALUES(N'بردسير');
INSERT INTO dbo.Cities(CityName) VALUES(N'بروات');
INSERT INTO dbo.Cities(CityName) VALUES(N'بروجرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بروجن');
INSERT INTO dbo.Cities(CityName) VALUES(N'بزغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بزمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بزنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بزينه رود');
INSERT INTO dbo.Cities(CityName) VALUES(N'بستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بستان  اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بستک');
INSERT INTO dbo.Cities(CityName) VALUES(N'بسطام');
INSERT INTO dbo.Cities(CityName) VALUES(N'بشارت');
INSERT INTO dbo.Cities(CityName) VALUES(N'بشاگرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بشرويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'بلداچي');
INSERT INTO dbo.Cities(CityName) VALUES(N'بلده');
INSERT INTO dbo.Cities(CityName) VALUES(N'بم');
INSERT INTO dbo.Cities(CityName) VALUES(N'بم  پشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'بمپور');
INSERT INTO dbo.Cities(CityName) VALUES(N'بن');
INSERT INTO dbo.Cities(CityName) VALUES(N'بناب');
INSERT INTO dbo.Cities(CityName) VALUES(N'بنارويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'بنت');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندپي شرقي');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندپي غربي');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرامام  خميني');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرانزلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرترکمن');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرجاسک');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرخمير');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندردير');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيدخت');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرديلم');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرريگ');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرعباس');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرگنگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرگز');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرگناوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرلنگه');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرماهشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'بن  رود');
INSERT INTO dbo.Cities(CityName) VALUES(N'بوانات');
INSERT INTO dbo.Cities(CityName) VALUES(N'بوئين  زهرا');
INSERT INTO dbo.Cities(CityName) VALUES(N'بوئين ومياندشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'بوشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'بوکان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بومهن');
INSERT INTO dbo.Cities(CityName) VALUES(N'بويراحمد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهاباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهار');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهبهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهرگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهمني');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهمن شير');
INSERT INTO dbo.Cities(CityName) VALUES(N'بهنمير');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيابان');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيارجمند');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيجار');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيرجند');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيرم');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيستون');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيضا');
INSERT INTO dbo.Cities(CityName) VALUES(N'بيله سوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'پاپي');
INSERT INTO dbo.Cities(CityName) VALUES(N'پابدانا');
INSERT INTO dbo.Cities(CityName) VALUES(N'پارس  اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'پاکدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'پاوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'پره سر');
INSERT INTO dbo.Cities(CityName) VALUES(N'پشت اب');
INSERT INTO dbo.Cities(CityName) VALUES(N'پشت کوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'پلدختر');
INSERT INTO dbo.Cities(CityName) VALUES(N'پلدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'پل سفيد');
INSERT INTO dbo.Cities(CityName) VALUES(N'پهله');
INSERT INTO dbo.Cities(CityName) VALUES(N'پيرانشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'پيربکران');
INSERT INTO dbo.Cities(CityName) VALUES(N'پيشوا');
INSERT INTO dbo.Cities(CityName) VALUES(N'پيشين');
INSERT INTO dbo.Cities(CityName) VALUES(N'تازه اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'تازه شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'تاکستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'تايباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'تجريش');
INSERT INTO dbo.Cities(CityName) VALUES(N'تحت جلگه');
INSERT INTO dbo.Cities(CityName) VALUES(N'تخت  سليمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'تربت  جام');
INSERT INTO dbo.Cities(CityName) VALUES(N'تربت  حيدريه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ترکمانچاي');
INSERT INTO dbo.Cities(CityName) VALUES(N'تفت');
INSERT INTO dbo.Cities(CityName) VALUES(N'تفرش');
INSERT INTO dbo.Cities(CityName) VALUES(N'تکاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'تلوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'تنب');
INSERT INTO dbo.Cities(CityName) VALUES(N'تنکابن');
INSERT INTO dbo.Cities(CityName) VALUES(N'تنگستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'تونکابن');
INSERT INTO dbo.Cities(CityName) VALUES(N'تولم');
INSERT INTO dbo.Cities(CityName) VALUES(N'تيران');
INSERT INTO dbo.Cities(CityName) VALUES(N'تيکمه  داش');
INSERT INTO dbo.Cities(CityName) VALUES(N'ثلاث باباجاني');
INSERT INTO dbo.Cities(CityName) VALUES(N'جاپلق');
INSERT INTO dbo.Cities(CityName) VALUES(N'جاجرم');
INSERT INTO dbo.Cities(CityName) VALUES(N'جالق');
INSERT INTO dbo.Cities(CityName) VALUES(N'جايزان');
INSERT INTO dbo.Cities(CityName) VALUES(N'جبالبارز');
INSERT INTO dbo.Cities(CityName) VALUES(N'جرقويه سفلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'جرقويه  عليا');
INSERT INTO dbo.Cities(CityName) VALUES(N'جعفراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'جعفريه');
INSERT INTO dbo.Cities(CityName) VALUES(N'جغتاي');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلفا');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلگه');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلگه  رخ');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلگه شوقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلگه  زاوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلگه  زوزن');
INSERT INTO dbo.Cities(CityName) VALUES(N'جلگه  سنخواست');
INSERT INTO dbo.Cities(CityName) VALUES(N'جم');
INSERT INTO dbo.Cities(CityName) VALUES(N'جنت شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'جندق');
INSERT INTO dbo.Cities(CityName) VALUES(N'جواداباد/جواديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'جواديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'جوانرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'جوپار');
INSERT INTO dbo.Cities(CityName) VALUES(N'جورقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'جونقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'جويبار');
INSERT INTO dbo.Cities(CityName) VALUES(N'جويم');
INSERT INTO dbo.Cities(CityName) VALUES(N'جوين');
INSERT INTO dbo.Cities(CityName) VALUES(N'جهرم');
INSERT INTO dbo.Cities(CityName) VALUES(N'جيرفت');
INSERT INTO dbo.Cities(CityName) VALUES(N'جيرنده');
INSERT INTO dbo.Cities(CityName) VALUES(N'چابکسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'چاپشلو');
INSERT INTO dbo.Cities(CityName) VALUES(N'چادگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'چاراويماق');
INSERT INTO dbo.Cities(CityName) VALUES(N'چارک');
INSERT INTO dbo.Cities(CityName) VALUES(N'چاروسا');
INSERT INTO dbo.Cities(CityName) VALUES(N'چالانچولان');
INSERT INTO dbo.Cities(CityName) VALUES(N'چالدران');
INSERT INTO dbo.Cities(CityName) VALUES(N'چالوس');
INSERT INTO dbo.Cities(CityName) VALUES(N'چابهار');
INSERT INTO dbo.Cities(CityName) VALUES(N'چايپاره');
INSERT INTO dbo.Cities(CityName) VALUES(N'چترود');
INSERT INTO dbo.Cities(CityName) VALUES(N'چرام');
INSERT INTO dbo.Cities(CityName) VALUES(N'چرمهين');
INSERT INTO dbo.Cities(CityName) VALUES(N'چغلوندي');
INSERT INTO dbo.Cities(CityName) VALUES(N'چقابل');
INSERT INTO dbo.Cities(CityName) VALUES(N'چلگرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'چمستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'چمگردان');
INSERT INTO dbo.Cities(CityName) VALUES(N'چناران');
INSERT INTO dbo.Cities(CityName) VALUES(N'چنگ  الماس');
INSERT INTO dbo.Cities(CityName) VALUES(N'چوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'چورزق طارم  عليا');
INSERT INTO dbo.Cities(CityName) VALUES(N'چهاربرج');
INSERT INTO dbo.Cities(CityName) VALUES(N'چهاردانگه');
INSERT INTO dbo.Cities(CityName) VALUES(N'چهاردولي');
INSERT INTO dbo.Cities(CityName) VALUES(N'چهارمحال وبختياري');
INSERT INTO dbo.Cities(CityName) VALUES(N'حاجي اباد هرمزگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'حبيب اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'حسن اباد جرقويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'حسين آباد رفسنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'حلب');
INSERT INTO dbo.Cities(CityName) VALUES(N'حميديا');
INSERT INTO dbo.Cities(CityName) VALUES(N'حميديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'حميل');
INSERT INTO dbo.Cities(CityName) VALUES(N'حنا');
INSERT INTO dbo.Cities(CityName) VALUES(N'خارک');
INSERT INTO dbo.Cities(CityName) VALUES(N'خاش');
INSERT INTO dbo.Cities(CityName) VALUES(N'خامنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'خان ببين');
INSERT INTO dbo.Cities(CityName) VALUES(N'خانميرزا');
INSERT INTO dbo.Cities(CityName) VALUES(N'خانوک');
INSERT INTO dbo.Cities(CityName) VALUES(N'خاوران');
INSERT INTO dbo.Cities(CityName) VALUES(N'خاورميراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خداافرين');
INSERT INTO dbo.Cities(CityName) VALUES(N'خدابنده');
INSERT INTO dbo.Cities(CityName) VALUES(N'خراجو');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرامه وکربال');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرانق');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرم بيد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرم اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرمدره');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرم دشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرمشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرو');
INSERT INTO dbo.Cities(CityName) VALUES(N'خروانق');
INSERT INTO dbo.Cities(CityName) VALUES(N'خزل');
INSERT INTO dbo.Cities(CityName) VALUES(N'خسروشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'خشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'خشت وکمارج');
INSERT INTO dbo.Cities(CityName) VALUES(N'خشکبيجار');
INSERT INTO dbo.Cities(CityName) VALUES(N'خضراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خضري  دشت  بيا');
INSERT INTO dbo.Cities(CityName) VALUES(N'خفر');
INSERT INTO dbo.Cities(CityName) VALUES(N'خلجستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خلخال');
INSERT INTO dbo.Cities(CityName) VALUES(N'خليغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خليل اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خمارلو');
INSERT INTO dbo.Cities(CityName) VALUES(N'خمام');
INSERT INTO dbo.Cities(CityName) VALUES(N'خمير');
INSERT INTO dbo.Cities(CityName) VALUES(N'خمين');
INSERT INTO dbo.Cities(CityName) VALUES(N'خنج');
INSERT INTO dbo.Cities(CityName) VALUES(N'خنداب');
INSERT INTO dbo.Cities(CityName) VALUES(N'خواجه');
INSERT INTO dbo.Cities(CityName) VALUES(N'خواف');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوانسار');
INSERT INTO dbo.Cities(CityName) VALUES(N'خور');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوراسگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خورزوق');
INSERT INTO dbo.Cities(CityName) VALUES(N'خورش رستم');
INSERT INTO dbo.Cities(CityName) VALUES(N'خورکام');
INSERT INTO dbo.Cities(CityName) VALUES(N'خورموج');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوروبيابانک');
INSERT INTO dbo.Cities(CityName) VALUES(N'دره شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوزستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوسف');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوشاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'دلگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوي');
INSERT INTO dbo.Cities(CityName) VALUES(N'داراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'داران  )فريدن (');
INSERT INTO dbo.Cities(CityName) VALUES(N'داريان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دالکي');
INSERT INTO dbo.Cities(CityName) VALUES(N'دامغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دامنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'دانسفهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'داورزن');
INSERT INTO dbo.Cities(CityName) VALUES(N'درب  بهشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'درچه');
INSERT INTO dbo.Cities(CityName) VALUES(N'دررود');
INSERT INTO dbo.Cities(CityName) VALUES(N'درگز');
INSERT INTO dbo.Cities(CityName) VALUES(N'درميان');
INSERT INTO dbo.Cities(CityName) VALUES(N'درودزن');
INSERT INTO dbo.Cities(CityName) VALUES(N'دزفول');
INSERT INTO dbo.Cities(CityName) VALUES(N'دستگرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'دستگردان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشت ازادگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشتستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشتک');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشتي');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشتياري');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشمن زياري');
INSERT INTO dbo.Cities(CityName) VALUES(N'دلفان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دلند');
INSERT INTO dbo.Cities(CityName) VALUES(N'دلوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'دليجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دماوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'دندي');
INSERT INTO dbo.Cities(CityName) VALUES(N'دودانگه');
INSERT INTO dbo.Cities(CityName) VALUES(N'دورود');
INSERT INTO dbo.Cities(CityName) VALUES(N'دوره چگني');
INSERT INTO dbo.Cities(CityName) VALUES(N'دوگنبدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دولت اباد اصفهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهاقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهبارز');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهج');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهدز');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهق');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهگلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهلران');
INSERT INTO dbo.Cities(CityName) VALUES(N'ديباج');
INSERT INTO dbo.Cities(CityName) VALUES(N'دير');
INSERT INTO dbo.Cities(CityName) VALUES(N'رحيم اباد رودسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ديزيچه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ديشموک');
INSERT INTO dbo.Cities(CityName) VALUES(N'ديلم');
INSERT INTO dbo.Cities(CityName) VALUES(N'ديلمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دينور');
INSERT INTO dbo.Cities(CityName) VALUES(N'ديواندره');
INSERT INTO dbo.Cities(CityName) VALUES(N'رابر');
INSERT INTO dbo.Cities(CityName) VALUES(N'راز');
INSERT INTO dbo.Cities(CityName) VALUES(N'رازوجرگلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رامسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'رامشير');
INSERT INTO dbo.Cities(CityName) VALUES(N'رامند');
INSERT INTO dbo.Cities(CityName) VALUES(N'رامهرمز');
INSERT INTO dbo.Cities(CityName) VALUES(N'راميان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رانکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'راور');
INSERT INTO dbo.Cities(CityName) VALUES(N'راين');
INSERT INTO dbo.Cities(CityName) VALUES(N'رباط');
INSERT INTO dbo.Cities(CityName) VALUES(N'رباط کريم');
INSERT INTO dbo.Cities(CityName) VALUES(N'رحمت آبادوبلوک');
INSERT INTO dbo.Cities(CityName) VALUES(N'رزن');
INSERT INTO dbo.Cities(CityName) VALUES(N'رستاق');
INSERT INTO dbo.Cities(CityName) VALUES(N'رستم');
INSERT INTO dbo.Cities(CityName) VALUES(N'رستم اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'رستم کلا');
INSERT INTO dbo.Cities(CityName) VALUES(N'رشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'رشتخوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'رضوانشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'رضي');
INSERT INTO dbo.Cities(CityName) VALUES(N'رفيع');
INSERT INTO dbo.Cities(CityName) VALUES(N'رمق');
INSERT INTO dbo.Cities(CityName) VALUES(N'روانسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'رفسنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'روداب');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبار گيلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبارالموت');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبارشهرستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبارقصران');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبست');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودخانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودهن');
INSERT INTO dbo.Cities(CityName) VALUES(N'رومشگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رونيز');
INSERT INTO dbo.Cities(CityName) VALUES(N'رضويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'رهنان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ري');
INSERT INTO dbo.Cities(CityName) VALUES(N'ريگ');
INSERT INTO dbo.Cities(CityName) VALUES(N'ريگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'رينه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ريوش');
INSERT INTO dbo.Cities(CityName) VALUES(N'زابل');
INSERT INTO dbo.Cities(CityName) VALUES(N'زابلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'زارج');
INSERT INTO dbo.Cities(CityName) VALUES(N'زاغه');
INSERT INTO dbo.Cities(CityName) VALUES(N'زاليان');
INSERT INTO dbo.Cities(CityName) VALUES(N'زاويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'زاهدشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'زبرخان');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرندساوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرنق');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرين دشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرين  رود');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرين آباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرين  شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ززوماهرو');
INSERT INTO dbo.Cities(CityName) VALUES(N'زنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلوانق');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلور');
INSERT INTO dbo.Cities(CityName) VALUES(N'کليبر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کليشادوسودرجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کمال  شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کمره');
INSERT INTO dbo.Cities(CityName) VALUES(N'کميجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کن');
INSERT INTO dbo.Cities(CityName) VALUES(N'کنارتخته');
INSERT INTO dbo.Cities(CityName) VALUES(N'کنارک');
INSERT INTO dbo.Cities(CityName) VALUES(N'کندوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کنگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کنگاور');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوثر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوچصفهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کورائيم');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوزران');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوشک');
INSERT INTO dbo.Cities(CityName) VALUES(N'کومله');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوناني');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهبنان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهپايه');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهسار');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهساران');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهسرخ');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهمره');
INSERT INTO dbo.Cities(CityName) VALUES(N'کويرات');
INSERT INTO dbo.Cities(CityName) VALUES(N'کهريزک');
INSERT INTO dbo.Cities(CityName) VALUES(N'کهک');
INSERT INTO dbo.Cities(CityName) VALUES(N'کهنوج');
INSERT INTO dbo.Cities(CityName) VALUES(N'کيار');
INSERT INTO dbo.Cities(CityName) VALUES(N'کياسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'بندرکياشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کياکلا');
INSERT INTO dbo.Cities(CityName) VALUES(N'کيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کيان شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کيش');
INSERT INTO dbo.Cities(CityName) VALUES(N'کيلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گاليکش');
INSERT INTO dbo.Cities(CityName) VALUES(N'گاوبندي');
INSERT INTO dbo.Cities(CityName) VALUES(N'گتوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'گچساران');
INSERT INTO dbo.Cities(CityName) VALUES(N'گراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'گراش');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرکن  جنوبي');
INSERT INTO dbo.Cities(CityName) VALUES(N'کن  شمالي  )پيربکران  (');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرگانرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرماب');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرمخان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرمسار');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرمه');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرمي');
INSERT INTO dbo.Cities(CityName) VALUES(N'گز');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلباف');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلبهار');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلپايگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گل تپه');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلزار');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گلوگاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'گميشان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گميش  تپه');
INSERT INTO dbo.Cities(CityName) VALUES(N'گناباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'گناوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'گنبدکاوس');
INSERT INTO dbo.Cities(CityName) VALUES(N'گندمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گنگ');
INSERT INTO dbo.Cities(CityName) VALUES(N'گواور');
INSERT INTO dbo.Cities(CityName) VALUES(N'گوراب  زرنيخ');
INSERT INTO dbo.Cities(CityName) VALUES(N'گوگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گوگد');
INSERT INTO dbo.Cities(CityName) VALUES(N'گهرو');
INSERT INTO dbo.Cities(CityName) VALUES(N'گهواره');
INSERT INTO dbo.Cities(CityName) VALUES(N'گيل خواران');
INSERT INTO dbo.Cities(CityName) VALUES(N'گيلانغرب');
INSERT INTO dbo.Cities(CityName) VALUES(N'گيوي');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لار');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاران');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاريجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاشار');
INSERT INTO dbo.Cities(CityName) VALUES(N'لالجين');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاله کنار');
INSERT INTO dbo.Cities(CityName) VALUES(N'لالي');
INSERT INTO dbo.Cities(CityName) VALUES(N'لامرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاهرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاهيجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لردگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ملارد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ملاير');
INSERT INTO dbo.Cities(CityName) VALUES(N'ملکان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ممسني');
INSERT INTO dbo.Cities(CityName) VALUES(N'ممقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'منجيل');
INSERT INTO dbo.Cities(CityName) VALUES(N'منوجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'موچش');
INSERT INTO dbo.Cities(CityName) VALUES(N'موسيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مومن اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهاباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهديشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهران');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهربان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهردشت  )دهق (');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهريز');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميامي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميان جلگه');
INSERT INTO dbo.Cities(CityName) VALUES(N'مياندواب');
INSERT INTO dbo.Cities(CityName) VALUES(N'مياندورود');
INSERT INTO dbo.Cities(CityName) VALUES(N'هيرمند');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميانکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميبد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميرجاوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميرزاکوچک  جنگلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميمند');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميمه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميناب');
INSERT INTO dbo.Cities(CityName) VALUES(N'مينو');
INSERT INTO dbo.Cities(CityName) VALUES(N'مينودشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'مينوشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'نائين');
INSERT INTO dbo.Cities(CityName) VALUES(N'نازلو');
INSERT INTO dbo.Cities(CityName) VALUES(N'ناغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'نالوس');
INSERT INTO dbo.Cities(CityName) VALUES(N'نجف شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'نجف اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ندوشن');
INSERT INTO dbo.Cities(CityName) VALUES(N'نراق');
INSERT INTO dbo.Cities(CityName) VALUES(N'نرماشير');
INSERT INTO dbo.Cities(CityName) VALUES(N'نشتارود');
INSERT INTO dbo.Cities(CityName) VALUES(N'نصراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'نصرت اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'نطنز');
INSERT INTO dbo.Cities(CityName) VALUES(N'نظراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'نظرکهريزي');
INSERT INTO dbo.Cities(CityName) VALUES(N'نقاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'نقده');
INSERT INTO dbo.Cities(CityName) VALUES(N'نکاء');
INSERT INTO dbo.Cities(CityName) VALUES(N'نگار');
INSERT INTO dbo.Cities(CityName) VALUES(N'نگور');
INSERT INTO dbo.Cities(CityName) VALUES(N'نمشير');
INSERT INTO dbo.Cities(CityName) VALUES(N'نمين');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوبران');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوبندگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوخندان');
INSERT INTO dbo.Cities(CityName) VALUES(N'نودشه');
INSERT INTO dbo.Cities(CityName) VALUES(N'نور');
INSERT INTO dbo.Cities(CityName) VALUES(N'نورآباد ممسني');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوسود');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوشين');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوفل  لوشاتو');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوق');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوک اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوکنده');
INSERT INTO dbo.Cities(CityName) VALUES(N'نهاوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'نهبندان');
INSERT INTO dbo.Cities(CityName) VALUES(N'نياسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'نير اردبيل');
INSERT INTO dbo.Cities(CityName) VALUES(N'نيريز');
INSERT INTO dbo.Cities(CityName) VALUES(N'نيشابور');
INSERT INTO dbo.Cities(CityName) VALUES(N'نيک اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'نيک  شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'نيمبلوک');
INSERT INTO dbo.Cities(CityName) VALUES(N'نيمور');
INSERT INTO dbo.Cities(CityName) VALUES(N'واجارگاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'وايقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'وحيديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ورامين');
INSERT INTO dbo.Cities(CityName) VALUES(N'ورزقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ورزنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ورنامخواست');
INSERT INTO dbo.Cities(CityName) VALUES(N'وزوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'وزينه');
INSERT INTO dbo.Cities(CityName) VALUES(N'وفس');
INSERT INTO dbo.Cities(CityName) VALUES(N'ولايت  )ولايت  جم  (');
INSERT INTO dbo.Cities(CityName) VALUES(N'ونک');
INSERT INTO dbo.Cities(CityName) VALUES(N'ويس');
INSERT INTO dbo.Cities(CityName) VALUES(N'ويسيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ويلکيج');
INSERT INTO dbo.Cities(CityName) VALUES(N'هادي شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'هرات');
INSERT INTO dbo.Cities(CityName) VALUES(N'هرات ومروست )خاتم  (');
INSERT INTO dbo.Cities(CityName) VALUES(N'هرسين');
INSERT INTO dbo.Cities(CityName) VALUES(N'هرمز');
INSERT INTO dbo.Cities(CityName) VALUES(N'هرند');
INSERT INTO dbo.Cities(CityName) VALUES(N'هريس');
INSERT INTO dbo.Cities(CityName) VALUES(N'هزارجريب');
INSERT INTO dbo.Cities(CityName) VALUES(N'هشتپر');
INSERT INTO dbo.Cities(CityName) VALUES(N'هشتجين');
INSERT INTO dbo.Cities(CityName) VALUES(N'هشترود');
INSERT INTO dbo.Cities(CityName) VALUES(N'هشتگرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'هفتگل');
INSERT INTO dbo.Cities(CityName) VALUES(N'هفشجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'هليلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'همدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'هندودر');
INSERT INTO dbo.Cities(CityName) VALUES(N'هنديجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'هوراند');
INSERT INTO dbo.Cities(CityName) VALUES(N'هويزه');
INSERT INTO dbo.Cities(CityName) VALUES(N'هيدج');
INSERT INTO dbo.Cities(CityName) VALUES(N'هير');
INSERT INTO dbo.Cities(CityName) VALUES(N'ياسوج');
INSERT INTO dbo.Cities(CityName) VALUES(N'ياسوکند');
INSERT INTO dbo.Cities(CityName) VALUES(N'يامچي');
INSERT INTO dbo.Cities(CityName) VALUES(N'يانه سر');
INSERT INTO dbo.Cities(CityName) VALUES(N'يزد');
INSERT INTO dbo.Cities(CityName) VALUES(N'لرستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لشت  نشاي');
INSERT INTO dbo.Cities(CityName) VALUES(N'لطف آباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'لنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لنده');
INSERT INTO dbo.Cities(CityName) VALUES(N'لنگرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'لواسان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لواسانات');
INSERT INTO dbo.Cities(CityName) VALUES(N'لوداب');
INSERT INTO dbo.Cities(CityName) VALUES(N'لوشان');
INSERT INTO dbo.Cities(CityName) VALUES(N'لومار');
INSERT INTO dbo.Cities(CityName) VALUES(N'ليکک');
INSERT INTO dbo.Cities(CityName) VALUES(N'ليلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مارگون');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماسال');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماسوله');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماکو');
INSERT INTO dbo.Cities(CityName) VALUES(N'مامونيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'مانه وسملقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماهدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماه نشان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماهورميلاتي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ماهيدشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'مبارکه');
INSERT INTO dbo.Cities(CityName) VALUES(N'مجن');
INSERT INTO dbo.Cities(CityName) VALUES(N'محلات');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمداباد بم');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمدشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمديار');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمودآبادنمونه');
INSERT INTO dbo.Cities(CityName) VALUES(N'محموداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمودوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'محي اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'مراغه');
INSERT INTO dbo.Cities(CityName) VALUES(N'مراوه تپه');
INSERT INTO dbo.Cities(CityName) VALUES(N'مرجقل /تولم شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'مرحمت اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'مرزداران');
INSERT INTO dbo.Cities(CityName) VALUES(N'مرزن اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'مرند');
INSERT INTO dbo.Cities(CityName) VALUES(N'مرودشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'مروست');
INSERT INTO dbo.Cities(CityName) VALUES(N'مريانج');
INSERT INTO dbo.Cities(CityName) VALUES(N'مريوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مسجدسليمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مشکين دشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'مشکين  شرقي');
INSERT INTO dbo.Cities(CityName) VALUES(N'مشگين  شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'مشهدمرغاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'مصيري');
INSERT INTO dbo.Cities(CityName) VALUES(N'معمولان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مقاومت');
INSERT INTO dbo.Cities(CityName) VALUES(N'ملاثاني');
INSERT INTO dbo.Cities(CityName) VALUES(N'تبريز');
INSERT INTO dbo.Cities(CityName) VALUES(N'تهران');
INSERT INTO dbo.Cities(CityName) VALUES(N'زاهدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مشهد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خميني  شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'هفت  تپه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهرري');
INSERT INTO dbo.Cities(CityName) VALUES(N'تالش');
INSERT INTO dbo.Cities(CityName) VALUES(N'تيران  وکرون');
INSERT INTO dbo.Cities(CityName) VALUES(N'اردکان  فارس');
INSERT INTO dbo.Cities(CityName) VALUES(N'حاجي اباد داراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'حاجي اباد زرين دشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'حاجي اباد قائنات');
INSERT INTO dbo.Cities(CityName) VALUES(N'حسن اباد قم');
INSERT INTO dbo.Cities(CityName) VALUES(N'نير تفت');
INSERT INTO dbo.Cities(CityName) VALUES(N'مهاباد اردستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميمه  دهلران');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوراباددلفان');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوراباد مبارکه');
INSERT INTO dbo.Cities(CityName) VALUES(N'خرم اباد تنکابن');
INSERT INTO dbo.Cities(CityName) VALUES(N'دولت اباد تربت حيدريه');
INSERT INTO dbo.Cities(CityName) VALUES(N'رحيم اباد ساوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'رودبار کهنوج');
INSERT INTO dbo.Cities(CityName) VALUES(N'صالح اباد مهران');
INSERT INTO dbo.Cities(CityName) VALUES(N'صالح اباد خراسان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيروزاباد کرمانشاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيروزاباد لرستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمداباد زابل');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمداباد اصفهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشنويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اطاقور');
INSERT INTO dbo.Cities(CityName) VALUES(N'املش');
INSERT INTO dbo.Cities(CityName) VALUES(N'اميراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'باباحيدر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ترکمن');
INSERT INTO dbo.Cities(CityName) VALUES(N'تويسرکان');
INSERT INTO dbo.Cities(CityName) VALUES(N'جره وبالاده');
INSERT INTO dbo.Cities(CityName) VALUES(N'جوکار');
INSERT INTO dbo.Cities(CityName) VALUES(N'راسک  وفيروزاباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سامن');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشوراده');
INSERT INTO dbo.Cities(CityName) VALUES(N'گله دار');
INSERT INTO dbo.Cities(CityName) VALUES(N'مغان )دشت مغان (');
INSERT INTO dbo.Cities(CityName) VALUES(N'گرگر');
INSERT INTO dbo.Cities(CityName) VALUES(N'علمدار');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاه ابادماکو');
INSERT INTO dbo.Cities(CityName) VALUES(N'نفت  شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'اورامانات');
INSERT INTO dbo.Cities(CityName) VALUES(N'نوسارد');
INSERT INTO dbo.Cities(CityName) VALUES(N'باباجاني');
INSERT INTO dbo.Cities(CityName) VALUES(N'شراط وپيشخور');
INSERT INTO dbo.Cities(CityName) VALUES(N'خسروي');
INSERT INTO dbo.Cities(CityName) VALUES(N'صلبوخ');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشت  ميشان');
INSERT INTO dbo.Cities(CityName) VALUES(N'حونيزه');
INSERT INTO dbo.Cities(CityName) VALUES(N'لانده');
INSERT INTO dbo.Cities(CityName) VALUES(N'خلف اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ويزيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دوراه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ملاوي');
INSERT INTO dbo.Cities(CityName) VALUES(N'اشتارني');
INSERT INTO dbo.Cities(CityName) VALUES(N'صميکان');
INSERT INTO dbo.Cities(CityName) VALUES(N'دووين');
INSERT INTO dbo.Cities(CityName) VALUES(N'معلم  کلايه');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرندکرمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميگون');
INSERT INTO dbo.Cities(CityName) VALUES(N'شمشک');
INSERT INTO dbo.Cities(CityName) VALUES(N'الموت');
INSERT INTO dbo.Cities(CityName) VALUES(N'جاجرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابعلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'فرديس');
INSERT INTO dbo.Cities(CityName) VALUES(N'غازيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'پيربازار');
INSERT INTO dbo.Cities(CityName) VALUES(N'چوکا');
INSERT INTO dbo.Cities(CityName) VALUES(N'مانک');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشت  ناز');
INSERT INTO dbo.Cities(CityName) VALUES(N'پهلوي دژ');
INSERT INTO dbo.Cities(CityName) VALUES(N'داش  برون');
INSERT INTO dbo.Cities(CityName) VALUES(N'دشت  گرگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'امامشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنگسر');
INSERT INTO dbo.Cities(CityName) VALUES(N'صيداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'اردکان  هرمزگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'تيرتاش');
INSERT INTO dbo.Cities(CityName) VALUES(N'قره  سو');
INSERT INTO dbo.Cities(CityName) VALUES(N'ده خرقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاهروداذربايجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنجبد');
INSERT INTO dbo.Cities(CityName) VALUES(N'خروش  رستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خيبر');
INSERT INTO dbo.Cities(CityName) VALUES(N'هراند');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارسباران');
INSERT INTO dbo.Cities(CityName) VALUES(N'گاوگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراسکند');
INSERT INTO dbo.Cities(CityName) VALUES(N'دهندره');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراسياب  فر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوک  کرمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'چوپار');
INSERT INTO dbo.Cities(CityName) VALUES(N'چگني');
INSERT INTO dbo.Cities(CityName) VALUES(N'زيرخان');
INSERT INTO dbo.Cities(CityName) VALUES(N'گچسران');
INSERT INTO dbo.Cities(CityName) VALUES(N'طوس');
INSERT INTO dbo.Cities(CityName) VALUES(N'جرگلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'اخوره');
INSERT INTO dbo.Cities(CityName) VALUES(N'قمشه');
INSERT INTO dbo.Cities(CityName) VALUES(N'خوانق');
INSERT INTO dbo.Cities(CityName) VALUES(N'لاوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ايرانکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'قهپايه');
INSERT INTO dbo.Cities(CityName) VALUES(N'قنوح');
INSERT INTO dbo.Cities(CityName) VALUES(N'ميرانشاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'خاوه وميراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'پيامان');
INSERT INTO dbo.Cities(CityName) VALUES(N'الات');
INSERT INTO dbo.Cities(CityName) VALUES(N'گروس');
INSERT INTO dbo.Cities(CityName) VALUES(N'فين  خمير');
INSERT INTO dbo.Cities(CityName) VALUES(N'گسسه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابلاغ سرو');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابسک');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابکنار');
INSERT INTO dbo.Cities(CityName) VALUES(N'ابيانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'اغميون');
INSERT INTO dbo.Cities(CityName) VALUES(N'سردشت  بندر');
INSERT INTO dbo.Cities(CityName) VALUES(N'زنجانرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'زنگي اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'زنور');
INSERT INTO dbo.Cities(CityName) VALUES(N'زواره');
INSERT INTO dbo.Cities(CityName) VALUES(N'زهک');
INSERT INTO dbo.Cities(CityName) VALUES(N'زيداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'زيدون');
INSERT INTO dbo.Cities(CityName) VALUES(N'زيراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'زيرکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'زيويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ساحلي  )دلوار(');
INSERT INTO dbo.Cities(CityName) VALUES(N'ساردوئيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'ساري');
INSERT INTO dbo.Cities(CityName) VALUES(N'سامان');
INSERT INTO dbo.Cities(CityName) VALUES(N'ساوجبلاغ');
INSERT INTO dbo.Cities(CityName) VALUES(N'ساوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سبزوار');
INSERT INTO dbo.Cities(CityName) VALUES(N'سپيدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سجاس');
INSERT INTO dbo.Cities(CityName) VALUES(N'سجاسرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'سده');
INSERT INTO dbo.Cities(CityName) VALUES(N'سده لنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراب');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراب  دوره');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراب باغ');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرابله');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراجو');
INSERT INTO dbo.Cities(CityName) VALUES(N'سراوان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرايان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرباز');
INSERT INTO dbo.Cities(CityName) VALUES(N'سربند');
INSERT INTO dbo.Cities(CityName) VALUES(N'سورشجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سربيشه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرپل  ذهاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرچهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرحد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرخرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرخس');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرخه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سردرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'سردشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرشيو');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرعين');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرکان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرواباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سروستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سرولايت');
INSERT INTO dbo.Cities(CityName) VALUES(N'سريش اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سعادت شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'سعادت اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سعداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سفيددشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'سقز');
INSERT INTO dbo.Cities(CityName) VALUES(N'سگزي');
INSERT INTO dbo.Cities(CityName) VALUES(N'سلسله');
INSERT INTO dbo.Cities(CityName) VALUES(N'سلطان اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سلطانيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سلماس');
INSERT INTO dbo.Cities(CityName) VALUES(N'سلمانشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'سمنان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سميرم');
INSERT INTO dbo.Cities(CityName) VALUES(N'سميرم سفلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سندرک');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنقر');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنگر');
INSERT INTO dbo.Cities(CityName) VALUES(N'سنندج');
INSERT INTO dbo.Cities(CityName) VALUES(N'سوادکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سوران');
INSERT INTO dbo.Cities(CityName) VALUES(N'سورک');
INSERT INTO dbo.Cities(CityName) VALUES(N'سوريان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سوسنگرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'سوق');
INSERT INTO dbo.Cities(CityName) VALUES(N'سومار');
INSERT INTO dbo.Cities(CityName) VALUES(N'سياهکل');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيب وسوران');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيرجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيريک');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيس');
INSERT INTO dbo.Cities(CityName) VALUES(N'سي  سخت');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيلاخور');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيلوانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيمکان');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيمينه رود');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيه چشمه');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيه رود');
INSERT INTO dbo.Cities(CityName) VALUES(N'شادگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شازند');
INSERT INTO dbo.Cities(CityName) VALUES(N'شال');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاندرمن');
INSERT INTO dbo.Cities(CityName) VALUES(N'شانديز');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاوور');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاهدشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاهرود');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاهين  دژ');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاهين شهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'شبانکاره');
INSERT INTO dbo.Cities(CityName) VALUES(N'شبستر');
INSERT INTO dbo.Cities(CityName) VALUES(N'شرا');
INSERT INTO dbo.Cities(CityName) VALUES(N'شربيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شرفخانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شريف اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ششتمد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ششده');
INSERT INTO dbo.Cities(CityName) VALUES(N'ششده وقره بلاغ');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاهديه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شفت');
INSERT INTO dbo.Cities(CityName) VALUES(N'شلمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شلمزار');
INSERT INTO dbo.Cities(CityName) VALUES(N'شميرانات');
INSERT INTO dbo.Cities(CityName) VALUES(N'شنداباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'شوراب )کوهرنگ (');
INSERT INTO dbo.Cities(CityName) VALUES(N'شوسف');
INSERT INTO dbo.Cities(CityName) VALUES(N'شوش');
INSERT INTO dbo.Cities(CityName) VALUES(N'شوشتر');
INSERT INTO dbo.Cities(CityName) VALUES(N'شوط');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهاب');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهداد');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهربابک');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهرضا');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهرکرد');
INSERT INTO dbo.Cities(CityName) VALUES(N'مس  سرچشمه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهرکي وناروني');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهريار');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهميرزاد');
INSERT INTO dbo.Cities(CityName) VALUES(N'چمران');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيب اب');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيبکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيراز');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيرگاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيروان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيروان وچرداول');
INSERT INTO dbo.Cities(CityName) VALUES(N'شيرين سو');
INSERT INTO dbo.Cities(CityName) VALUES(N'صائين قلعه');
INSERT INTO dbo.Cities(CityName) VALUES(N'صالح اباد همدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'صباشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'صحنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'صدوق');
INSERT INTO dbo.Cities(CityName) VALUES(N'صغاد');
INSERT INTO dbo.Cities(CityName) VALUES(N'صفائيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'صفادشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'صفاشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'صوفيان');
INSERT INTO dbo.Cities(CityName) VALUES(N'صوماي  برادوسه');
INSERT INTO dbo.Cities(CityName) VALUES(N'صومعه  سرا');
INSERT INTO dbo.Cities(CityName) VALUES(N'صيدون');
INSERT INTO dbo.Cities(CityName) VALUES(N'ضيااباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'طارم');
INSERT INTO dbo.Cities(CityName) VALUES(N'طارم سفلي');
INSERT INTO dbo.Cities(CityName) VALUES(N'طاقانک');
INSERT INTO dbo.Cities(CityName) VALUES(N'طالخونچه');
INSERT INTO dbo.Cities(CityName) VALUES(N'طالقان');
INSERT INTO dbo.Cities(CityName) VALUES(N'طبس');
INSERT INTO dbo.Cities(CityName) VALUES(N'طرقبه');
INSERT INTO dbo.Cities(CityName) VALUES(N'طرهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'طسوج');
INSERT INTO dbo.Cities(CityName) VALUES(N'طوالش');
INSERT INTO dbo.Cities(CityName) VALUES(N'عباس  اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'عجب  شير');
INSERT INTO dbo.Cities(CityName) VALUES(N'عشق اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'عقدا');
INSERT INTO dbo.Cities(CityName) VALUES(N'علامرودشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'علمده /رويان');
INSERT INTO dbo.Cities(CityName) VALUES(N'علويجه');
INSERT INTO dbo.Cities(CityName) VALUES(N'علي  اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'عمارلو');
INSERT INTO dbo.Cities(CityName) VALUES(N'عنبراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'غرق اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'فارس');
INSERT INTO dbo.Cities(CityName) VALUES(N'فارسان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فارغان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فاروج');
INSERT INTO dbo.Cities(CityName) VALUES(N'فارياب');
INSERT INTO dbo.Cities(CityName) VALUES(N'فامنين');
INSERT INTO dbo.Cities(CityName) VALUES(N'فرادنبه');
INSERT INTO dbo.Cities(CityName) VALUES(N'فراشبند');
INSERT INTO dbo.Cities(CityName) VALUES(N'فراهان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فرخشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'فردوس');
INSERT INTO dbo.Cities(CityName) VALUES(N'فرمهين');
INSERT INTO dbo.Cities(CityName) VALUES(N'فريدن');
INSERT INTO dbo.Cities(CityName) VALUES(N'فريدونشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'فريدونکنار');
INSERT INTO dbo.Cities(CityName) VALUES(N'فريمان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فسا');
INSERT INTO dbo.Cities(CityName) VALUES(N'فشافويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'فشم');
INSERT INTO dbo.Cities(CityName) VALUES(N'فلارد');
INSERT INTO dbo.Cities(CityName) VALUES(N'فلاورجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فنوج');
INSERT INTO dbo.Cities(CityName) VALUES(N'فورگ');
INSERT INTO dbo.Cities(CityName) VALUES(N'قطب اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'فولادشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'فومن');
INSERT INTO dbo.Cities(CityName) VALUES(N'فهرج');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيرورق');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيروز');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيروزآباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيروزان');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيروزکوه');
INSERT INTO dbo.Cities(CityName) VALUES(N'فيض اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'فين کاشان');
INSERT INTO dbo.Cities(CityName) VALUES(N'قائمشهر');
INSERT INTO dbo.Cities(CityName) VALUES(N'قائميه');
INSERT INTO dbo.Cities(CityName) VALUES(N'قائنات');
INSERT INTO dbo.Cities(CityName) VALUES(N'قادراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'قائن');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهرقدس');
INSERT INTO dbo.Cities(CityName) VALUES(N'قدمگاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'قرچک');
INSERT INTO dbo.Cities(CityName) VALUES(N'قروه');
INSERT INTO dbo.Cities(CityName) VALUES(N'قروه درجزين');
INSERT INTO dbo.Cities(CityName) VALUES(N'قره اغاج');
INSERT INTO dbo.Cities(CityName) VALUES(N'قره ضياء الدين');
INSERT INTO dbo.Cities(CityName) VALUES(N'قزوين');
INSERT INTO dbo.Cities(CityName) VALUES(N'قشلاق  دشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'قشم');
INSERT INTO dbo.Cities(CityName) VALUES(N'قصرشيرين');
INSERT INTO dbo.Cities(CityName) VALUES(N'قصرقند');
INSERT INTO dbo.Cities(CityName) VALUES(N'قطور');
INSERT INTO dbo.Cities(CityName) VALUES(N'قلعه دره ملک شاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'قلعه گنج');
INSERT INTO dbo.Cities(CityName) VALUES(N'قلقل رود');
INSERT INTO dbo.Cities(CityName) VALUES(N'قم');
INSERT INTO dbo.Cities(CityName) VALUES(N'قمصر');
INSERT INTO dbo.Cities(CityName) VALUES(N'قنقري');
INSERT INTO dbo.Cities(CityName) VALUES(N'قوچان');
INSERT INTO dbo.Cities(CityName) VALUES(N'قوشچي');
INSERT INTO dbo.Cities(CityName) VALUES(N'قهاوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'قهدريجان');
INSERT INTO dbo.Cities(CityName) VALUES(N'قيدار');
INSERT INTO dbo.Cities(CityName) VALUES(N'قيروکازين');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاخک');
INSERT INTO dbo.Cities(CityName) VALUES(N'کازرون');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاشان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاشمر');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاظم اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاغذکنان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاکاوند');
INSERT INTO dbo.Cities(CityName) VALUES(N'کاکي');
INSERT INTO dbo.Cities(CityName) VALUES(N'کامفيروز');
INSERT INTO dbo.Cities(CityName) VALUES(N'کامياران');
INSERT INTO dbo.Cities(CityName) VALUES(N'کبودراهنگ');
INSERT INTO dbo.Cities(CityName) VALUES(N'کتالم وسادات محله');
INSERT INTO dbo.Cities(CityName) VALUES(N'کجور');
INSERT INTO dbo.Cities(CityName) VALUES(N'کدکن');
INSERT INTO dbo.Cities(CityName) VALUES(N'کراني');
INSERT INTO dbo.Cities(CityName) VALUES(N'کربال');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرج');
INSERT INTO dbo.Cities(CityName) VALUES(N'کردستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کردکوي');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرديان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرفتوي');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرمانشاه');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرند');
INSERT INTO dbo.Cities(CityName) VALUES(N'کرون');
INSERT INTO dbo.Cities(CityName) VALUES(N'کشاورز');
INSERT INTO dbo.Cities(CityName) VALUES(N'کشکسراي');
INSERT INTO dbo.Cities(CityName) VALUES(N'کشکوئيه');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلات');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلاتوزان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلاته خيج');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلاچاي');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلاراباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلاردشت');
INSERT INTO dbo.Cities(CityName) VALUES(N'کلاله');
INSERT INTO dbo.Cities(CityName) VALUES(N'کجاباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'اسفهلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'زينجاب3');
INSERT INTO dbo.Cities(CityName) VALUES(N'زارچ');
INSERT INTO dbo.Cities(CityName) VALUES(N'عسلويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'کهکيلويه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهرفيروزه');
INSERT INTO dbo.Cities(CityName) VALUES(N'چکنه');
INSERT INTO dbo.Cities(CityName) VALUES(N'فين هرمزگان');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوکلان');
INSERT INTO dbo.Cities(CityName) VALUES(N'مود');
INSERT INTO dbo.Cities(CityName) VALUES(N'قهستان');
INSERT INTO dbo.Cities(CityName) VALUES(N'خضري');
INSERT INTO dbo.Cities(CityName) VALUES(N'کوهرنگ');
INSERT INTO dbo.Cities(CityName) VALUES(N'محمدان');
INSERT INTO dbo.Cities(CityName) VALUES(N'شهر صنعتي البرز');
INSERT INTO dbo.Cities(CityName) VALUES(N'تازه کند');
INSERT INTO dbo.Cities(CityName) VALUES(N'شاوور');
INSERT INTO dbo.Cities(CityName) VALUES(N'سيراف');
INSERT INTO dbo.Cities(CityName) VALUES(N'زرآباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'آسارا');
INSERT INTO dbo.Cities(CityName) VALUES(N'ارمغانخانه');
INSERT INTO dbo.Cities(CityName) VALUES(N'شميران');
INSERT INTO dbo.Cities(CityName) VALUES(N'تالش  هشتپر');
INSERT INTO dbo.Cities(CityName) VALUES(N'ترکمنچاي');
INSERT INTO dbo.Cities(CityName) VALUES(N'مياندرود)سورک (');
INSERT INTO dbo.Cities(CityName) VALUES(N'دولت  اباد');
INSERT INTO dbo.Cities(CityName) VALUES(N'ساير');
INSERT INTO dbo.Cities(CityName) VALUES(N'کشورهاوشهرهاي خارجي');
INSERT INTO dbo.Cities(CityName) VALUES(N'ناشناس');
